In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv('iris.csv')


from sklearn.preprocessing import LabelEncoder, OneHotEncoder
encoder = LabelEncoder()
df = df.drop(['Id'], axis=1)
df['Species']= encoder.fit_transform(df['Species'])
df

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0              5.1           3.5            1.4           0.2        0
1              4.9           3.0            1.4           0.2        0
2              4.7           3.2            1.3           0.2        0
3              4.6           3.1            1.5           0.2        0
4              5.0           3.6            1.4           0.2        0
..             ...           ...            ...           ...      ...
145            6.7           3.0            5.2           2.3        2
146            6.3           2.5            5.0           1.9        2
147            6.5           3.0            5.2           2.0        2
148            6.2           3.4            5.4           2.3        2
149            5.9           3.0            5.1           1.8        2

[150 rows x 5 columns]

In [2]:
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix
scaler = StandardScaler()
X_scaled = scaler.fit_transform(df)

df
X_scaled

array([[-9.00681170e-01,  1.03205722e+00, -1.34127240e+00,
        -1.31297673e+00, -1.22474487e+00],
       [-1.14301691e+00, -1.24957601e-01, -1.34127240e+00,
        -1.31297673e+00, -1.22474487e+00],
       [-1.38535265e+00,  3.37848329e-01, -1.39813811e+00,
        -1.31297673e+00, -1.22474487e+00],
       [-1.50652052e+00,  1.06445364e-01, -1.28440670e+00,
        -1.31297673e+00, -1.22474487e+00],
       [-1.02184904e+00,  1.26346019e+00, -1.34127240e+00,
        -1.31297673e+00, -1.22474487e+00],
       [-5.37177559e-01,  1.95766909e+00, -1.17067529e+00,
        -1.05003079e+00, -1.22474487e+00],
       [-1.50652052e+00,  8.00654259e-01, -1.34127240e+00,
        -1.18150376e+00, -1.22474487e+00],
       [-1.02184904e+00,  8.00654259e-01, -1.28440670e+00,
        -1.31297673e+00, -1.22474487e+00],
       [-1.74885626e+00, -3.56360566e-01, -1.34127240e+00,
        -1.31297673e+00, -1.22474487e+00],
       [-1.14301691e+00,  1.06445364e-01, -1.28440670e+00,
        -1.44444970e+00

In [3]:
x_columns = 4
X = df.iloc[:, :x_columns].values
y = df.iloc[:, x_columns].values
X_scaled = scaler.fit_transform(X)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.20, random_state=7)

from sklearn.linear_model import LogisticRegression
l_model = LogisticRegression(random_state=7, solver='lbfgs', multi_class='ovr')
l_model.fit(X_train, y_train)

y_pred = l_model.predict(X_test)
y_pred

array([2, 1, 0, 1, 1, 1, 2, 1, 0, 2, 2, 2, 0, 2, 0, 2, 2, 2, 0, 0, 1, 2,
       1, 1, 2, 2, 1, 1, 2, 2])

In [4]:
from sklearn.neighbors import KNeighborsClassifier
K = 4
k_model = KNeighborsClassifier(n_neighbors=K)
k_model.fit(X_train, y_train)
y_pred = k_model.predict(X_test)
y_pred
k_score = k_model.score(X_test, y_test)
k_score

0.9

In [5]:
from sklearn.svm import SVC
svm_model = SVC(max_iter = 100)

In [6]:
from sklearn.tree import DecisionTreeClassifier
tree_model = DecisionTreeClassifier(criterion = 'entropy', max_leaf_nodes = 50)

In [7]:
from sklearn.ensemble import RandomForestClassifier
RF_model = RandomForestClassifier(n_estimators = 100, bootstrap = True)

In [8]:
from sklearn.naive_bayes import GaussianNB
NB_model = GaussianNB()

In [9]:
all_models = [l_model, k_model, svm_model, tree_model, RF_model, NB_model]
all_models

[LogisticRegression(multi_class='ovr', random_state=7),
 KNeighborsClassifier(n_neighbors=4),
 SVC(max_iter=100),
 DecisionTreeClassifier(criterion='entropy', max_leaf_nodes=50),
 RandomForestClassifier(),
 GaussianNB()]

In [10]:
import matplotlib.pyplot as plt
import seaborn as sn

In [11]:
for i in all_models:
    print(i)
    i.fit(X_train, y_train)
    y_pred = i.predict(X_test)
    print(y_pred)
    s = i.score(X_test, y_test)
    print(f'Accuracy: {s}')
    print(confusion_matrix(y_test, y_pred))
    #sn.pairplot(df, hue = "Species").set_title('Algoritm Comparison')


LogisticRegression(multi_class='ovr', random_state=7)
[2 1 0 1 1 1 2 1 0 2 2 2 0 2 0 2 2 2 0 0 1 2 1 1 2 2 1 1 2 2]
Accuracy: 0.7333333333333333
[[6 1 0]
 [0 7 5]
 [0 2 9]]
KNeighborsClassifier(n_neighbors=4)
[2 1 0 1 1 0 1 1 0 1 1 1 0 2 0 1 2 2 0 0 1 2 1 1 2 1 1 1 2 2]
Accuracy: 0.9
[[ 7  0  0]
 [ 0 12  0]
 [ 0  3  8]]
SVC(max_iter=100)
[2 1 0 1 1 0 1 1 0 1 2 1 0 2 0 2 2 2 0 0 1 2 1 1 2 2 1 1 2 2]
Accuracy: 0.8666666666666667
[[ 7  0  0]
 [ 0 10  2]
 [ 0  2  9]]
DecisionTreeClassifier(criterion='entropy', max_leaf_nodes=50)
[2 1 0 1 1 0 1 1 0 1 1 1 0 2 0 2 2 2 0 0 1 2 1 1 1 2 1 1 2 2]
Accuracy: 0.8666666666666667
[[ 7  0  0]
 [ 0 11  1]
 [ 0  3  8]]
RandomForestClassifier()
[2 1 0 1 1 0 1 1 0 1 2 1 0 2 0 2 2 2 0 0 1 2 1 1 2 2 1 1 2 2]
Accuracy: 0.8666666666666667
[[ 7  0  0]
 [ 0 10  2]
 [ 0  2  9]]
GaussianNB()
[2 1 0 1 1 0 2 1 0 1 2 1 0 2 0 2 2 2 0 0 1 2 1 1 2 2 1 1 2 2]
Accuracy: 0.8333333333333334
[[7 0 0]
 [0 9 3]
 [0 2 9]]
